//! E6: the save-version safety net.
//!
//! `godot-rust/tests/saves/` holds one committed JSON save per `save_version`
//! ever shipped, and this file loads every one of them. It exists because
//! `ExpeditionState` grows constantly and the discipline that keeps old saves
//! loading was, until now, only a claim in a comment.
//!
//! **The rule this test enforces** (`docs/SHIP_PLAN.md` §9, "The
//! `ExpeditionState` rule"): a new field is appended at the end of the struct,
//! is `#[serde(default)]`, and never changes an existing field's meaning.
//! `CURRENT_SAVE_VERSION` bumps only when a field's meaning changes, and only
//! with a fixture for the old version committed alongside the bump.
//!
//! So: adding a field is free, and this test stays green on its own. Renaming
//! one, reordering the meaning of one, or dropping a `#[serde(default)]` breaks
//! `v1_minimal.json` immediately -- which is the whole point, because the
//! alternative is finding out inside a player's save file.
//!
//! The two v1 fixtures are not interchangeable:
//!
//! * `v1_minimal.json` is what an early save actually looked like: only the
//!   fields that existed at the original `save_version: 1`. It carries no
//!   `daily_spawn_records`, no `nightly_spawn_records`, no `hunters`, no
//!   `resolved_encounter_ids`, and its `pending_encounter` has no
//!   `estate_upgrade_id`. Every `#[serde(default)]` claim in `expedition.rs`
//!   depends on this file still loading.
//! * `v1_current.json` is a full round trip of today's state, generated by
//!   constructing a campaign, exercising it (midnight, travel, an encounter
//!   fought and won) and calling `to_json` -- never hand-written, so it cannot
//!   drift into a shape the code would not produce.
//!
//! Fixtures are enumerated from the directory, not listed here, so a fixture
//! committed for a future `save_version` is covered the moment it lands.

use std::collections::BTreeSet;
use std::path::{Path, PathBuf};

use project42_sim::*;

fn saves_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/saves")
}

/// Every `*.json` under `tests/saves/`, sorted, as (file name, contents).
fn fixtures() -> Vec<(String, String)> {
    let dir = saves_dir();
    let mut found: Vec<(String, String)> = std::fs::read_dir(&dir)
        .unwrap_or_else(|error| panic!("{} is readable: {error}", dir.display()))
        .map(|entry| entry.expect("directory entry").path())
        .filter(|path| {
            path.extension()
                .is_some_and(|extension| extension == "json")
        })
        .map(|path| {
            let name = path
                .file_name()
                .expect("fixture has a file name")
                .to_string_lossy()
                .into_owned();
            let contents = std::fs::read_to_string(&path)
                .unwrap_or_else(|error| panic!("{name} is readable: {error}"));
            (name, contents)
        })
        .collect();
    found.sort();
    assert!(
        !found.is_empty(),
        "{} must hold one fixture per shipped save_version",
        dir.display()
    );
    found
}

fn keys_of(json: &str) -> BTreeSet<String> {
    serde_json::from_str::<serde_json::Value>(json)
        .expect("fixture is JSON")
        .as_object()
        .expect("a save is a JSON object")
        .keys()
        .cloned()
        .collect()
}

/// A state in today's shape, used only as the reference for "which fields does
/// the current code write?".
fn a_current_save() -> ExpeditionState {
    ExpeditionState::new(
        1,
        vec!["character.protagonist.captain".into()],
        "world.cell.black_beach",
    )
    .expect("fresh campaign constructs")
}

#[test]
fn every_committed_fixture_still_loads() {
    for (name, contents) in fixtures() {
        let state = ExpeditionState::from_json(&contents)
            .unwrap_or_else(|error| panic!("{name} must still load: {error:?}"));

        assert!(
            state.save_version <= expedition::CURRENT_SAVE_VERSION,
            "{name} claims save_version {}, ahead of CURRENT_SAVE_VERSION {}",
            state.save_version,
            expedition::CURRENT_SAVE_VERSION
        );
        assert!(
            !state.legal_next_commands().is_empty(),
            "{name} loaded but offers the player nothing to do"
        );
    }
}

/// Every top-level key `ExpeditionState::to_json` writes today, as a literal.
///
/// A literal on purpose. S1 found that deriving this set from the serializer
/// under test made the migration suite blind to a field marked
/// `skip_serializing`: the field vanished from every save and the suite,
/// comparing the serializer to itself, agreed with it. Now the struct's
/// declared fields are written here by hand, in struct order, and the test
/// below holds the serializer to them. Adding a field means adding it here
/// -- and regenerating `v1_current.json` -- on purpose, which is the point.
const EXPECTED_CURRENT_KEYS: &[&str] = &[
    "save_version",
    "campaign_day",
    "time_segment",
    "party_ids",
    "active_location_id",
    "route_history",
    "supplies",
    "character_states",
    "named_person_memory",
    "habitat_states",
    "daily_spawn_records",
    "nightly_spawn_records",
    "hunters",
    "discoveries",
    "household_progress",
    "pending_encounter",
    "resolved_encounter_ids",
    "anchor_uses",
    "rng_seed",
    "factions",
    "recruitment",
    "ownership",
    "strategic_clock",
    "strategic_journal",
    "cthulhu_heat",
    "weather",
    "corruption",
    "forces",
];

fn expected_current_keys() -> BTreeSet<String> {
    EXPECTED_CURRENT_KEYS
        .iter()
        .map(|key| (*key).to_owned())
        .collect()
}

/// The serializer writes exactly the fields the struct declares: nothing
/// skipped, nothing renamed, nothing added without this list knowing. This is
/// the test S1 proved the suite was missing.
#[test]
fn the_current_save_writes_exactly_the_fields_the_struct_declares() {
    let written = keys_of(&a_current_save().to_json());
    let expected = expected_current_keys();
    let missing: Vec<&String> = expected.difference(&written).collect();
    let unexpected: Vec<&String> = written.difference(&expected).collect();
    assert!(
        missing.is_empty() && unexpected.is_empty(),
        "ExpeditionState::to_json and EXPECTED_CURRENT_KEYS disagree.\n\
         declared but not written (a skip_serializing, or a rename): {missing:?}\n\
         written but not declared (a new field -- add it to the list and \
         regenerate v1_current.json): {unexpected:?}"
    );
}

#[test]
fn fields_added_since_a_fixture_was_written_default_instead_of_failing() {
    // The literal, not the serializer: see EXPECTED_CURRENT_KEYS.
    let current_keys = expected_current_keys();

    for (name, contents) in fixtures() {
        let fixture_keys = keys_of(&contents);
        let added_since: Vec<&String> = current_keys.difference(&fixture_keys).collect();

        let state = ExpeditionState::from_json(&contents)
            .unwrap_or_else(|error| panic!("{name} must still load: {error:?}"));

        // Loading supplied a value for every field the fixture predates, so the
        // reloaded save writes today's full key set. A field that was renamed
        // rather than appended shows up here as a key the round trip lost.
        let reloaded_keys = keys_of(&state.to_json());
        for key in &current_keys {
            assert!(
                reloaded_keys.contains(key),
                "{name}: reloading dropped `{key}` -- a field's meaning changed \
                 without a CURRENT_SAVE_VERSION bump"
            );
        }

        // The defaulted collections come back empty rather than the load failing.
        if added_since.iter().any(|key| *key == "daily_spawn_records") {
            assert!(state.daily_spawn_records.is_empty(), "{name}");
        }
        if added_since
            .iter()
            .any(|key| *key == "nightly_spawn_records")
        {
            assert!(state.nightly_spawn_records.is_empty(), "{name}");
        }
        if added_since.iter().any(|key| *key == "hunters") {
            assert!(state.hunters.is_empty(), "{name}");
        }
        if added_since
            .iter()
            .any(|key| *key == "resolved_encounter_ids")
        {
            assert!(state.resolved_encounter_ids.is_empty(), "{name}");
        }
    }
}

/// The minimal v1 save is the one that actually bites: it predates every
/// `#[serde(default)]` field on `ExpeditionState`, so it is the file that fails
/// the moment one of those attributes is removed or a field is renamed.
#[test]
fn the_minimal_v1_save_predates_every_defaulted_field() {
    let contents = std::fs::read_to_string(saves_dir().join("v1_minimal.json"))
        .expect("the minimal v1 fixture is committed");
    let fixture_keys = keys_of(&contents);

    for added_later in [
        "daily_spawn_records",
        "nightly_spawn_records",
        "hunters",
        "resolved_encounter_ids",
    ] {
        assert!(
            !fixture_keys.contains(added_later),
            "v1_minimal.json must not carry `{added_later}`: it is the fixture \
             that proves saves written before that field still load"
        );
    }

    let state = ExpeditionState::from_json(&contents)
        .expect("a save written at the original save_version 1 still loads");
    assert_eq!(state.save_version, 1);
    assert!(state.daily_spawn_records.is_empty());
    assert!(state.nightly_spawn_records.is_empty());
    assert!(state.hunters.is_empty());
    assert!(state.resolved_encounter_ids.is_empty());
    // The nested default too: `EncounterState.estate_upgrade_id` was appended
    // after the original v1, so this fixture's pending encounter has no such key.
    let encounter = state
        .pending_encounter
        .as_ref()
        .expect("the minimal fixture is saved mid-encounter");
    assert!(encounter.estate_upgrade_id.is_none());
    assert!(!state.legal_next_commands().is_empty());
}

/// Every `save_version` the project has ever shipped needs a fixture; today
/// that is v1 alone. When `CURRENT_SAVE_VERSION` bumps, this fails until a
/// fixture for the new version is committed -- which is the rule stated above,
/// enforced rather than remembered.
#[test]
fn every_shipped_save_version_has_a_fixture() {
    let mut covered = BTreeSet::new();
    for (name, contents) in fixtures() {
        let state = ExpeditionState::from_json(&contents)
            .unwrap_or_else(|error| panic!("{name} must still load: {error:?}"));
        covered.insert(state.save_version);
    }
    for version in 1..=expedition::CURRENT_SAVE_VERSION {
        assert!(
            covered.contains(&version),
            "no fixture in tests/saves/ carries save_version {version}"
        );
    }
}
