// E9. Builds one Godot `.pck` per presentation pack under `packs/`.
//
// Why a staging project exists here. `packs/` sits at the repository root, not
// inside the Godot project at `game/`, so `res://` never contains it and the
// game project cannot export it. A pack is also deliberately not part of the
// game: it is a separate artifact that may or may not be installed, and the
// adult-store build is *the base build plus a pack*, never a second build of
// the game. So each pack is exported from a throwaway project under
// `work/pack-build/<id>/` whose entire `res://` is `packs/<id>/`. That project
// is generated on every run and is not a second copy of anything: it carries no
// scripts, no scenes, no autoloads and no GDExtension, only the pack's own
// files and the one export preset needed to pack them.
//
// The path inside the `.pck` is the contract. `game/scripts/content/pack_registry.gd`
// mounts a `.pck` with `ProjectSettings.load_resource_pack` and then reads its
// manifest from `res://packs/<pack id>/pack.json` — it derives that path from
// the file's own basename, because `tools/src/validate.mjs` holds a pack's `id`
// equal to its directory name. Staging the pack at `packs/<id>/` inside the
// throwaway project is what makes the manifest land exactly there, and the
// probe below proves it did rather than assuming it.
//
// Usage: node tools/src/build-pack.mjs [output directory]
// Output defaults to `work/packs/`. `GODOT` names the engine binary; otherwise
// `godot` is taken from PATH.

import { spawnSync } from "node:child_process";
import { cp, mkdir, readdir, readFile, rm, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { resolve, relative } from "node:path";
import process from "node:process";

const repo = resolve(import.meta.dirname, "../..");
const packsDirectory = resolve(repo, "packs");
const outputDirectory = resolve(repo, process.argv[2] ?? "work/packs");
const stagingRoot = resolve(repo, "work/pack-build");
const probeProject = resolve(stagingRoot, ".probe");
const godot = process.env.GODOT ?? "godot";

const PRESET_NAME = "Pack";

// The engine prints these when a resource, a script or an export step fails,
// and it can still exit zero afterwards — the lesson E2 paid for in
// tools/verify-godot.sh. A step whose output carries one of them is a failure
// here for the same reason.
const ENGINE_ERROR_MARKERS = ["SCRIPT ERROR:", "ERROR:"];

function fail(message) {
  console.error(`build-pack: ${message}`);
  process.exitCode = 1;
}

function runGodot(what, args) {
  const result = spawnSync(godot, args, { encoding: "utf8", maxBuffer: 64 * 1024 * 1024 });
  if (result.error) {
    fail(`${what}: could not run ${godot}: ${result.error.message}`);
    return null;
  }
  const output = `${result.stdout ?? ""}${result.stderr ?? ""}`;
  if (result.status !== 0) {
    fail(`${what}: ${godot} exited ${result.status}\n${output}`);
    return null;
  }
  const marker = ENGINE_ERROR_MARKERS.find(value => output.includes(value));
  if (marker !== undefined) {
    fail(`${what}: the engine exited zero but printed "${marker}"\n${output}`);
    return null;
  }
  return output;
}

function projectFile(name) {
  return `; Generated by tools/src/build-pack.mjs. Not committed, not edited by hand.\nconfig_version=5\n\n[application]\n\nconfig/name="${name}"\n`;
}

// One Linux preset, because a `.pck` has no platform: `--export-pack` writes the
// packed resources and never touches an export template. `export_filter` takes
// every resource and `include_filter` additionally takes the pack's plain files
// (a still plate or a `.txt` marker is not a Godot resource and would otherwise
// be left out of the pack that declares it).
const EXPORT_PRESETS = `[preset.0]

name="${PRESET_NAME}"
platform="Linux"
runnable=true
dedicated_server=false
custom_features=""
export_filter="all_resources"
include_filter="packs/*"
exclude_filter=""
export_path=""
patches=PackedStringArray()
encryption_include_filters=""
encryption_exclude_filters=""
seed=0
encrypt_pck=false
encrypt_directory=false
script_export_mode=2

[preset.0.options]

custom_template/debug=""
custom_template/release=""
debug/export_console_wrapper=1
binary_format/embed_pck=false
texture_format/s3tc_bptc=true
texture_format/etc2_astc=false
binary_format/architecture="x86_64"
ssh_remote_deploy/enabled=false
`;

// Mounts a finished .pck into an empty project and reads the manifest back out
// of it at the path the registry looks for. This is the whole point of the
// script, so it is checked rather than assumed: an export that silently drops
// pack.json, or lands it one directory off, produces a .pck that
// ContentPackRegistry refuses at runtime with "the mounted resource pack
// carries no pack.json", and that must be a build failure, not a launch-day
// surprise.
const PROBE_SCRIPT = `extends SceneTree

## Generated by tools/src/build-pack.mjs. Mounts one built pack and proves its
## manifest and every asset it declares are inside it, where B10's
## ContentPackRegistry reads them.

func _initialize() -> void:
\tvar arguments := OS.get_cmdline_user_args()
\tif arguments.size() != 2:
\t\tprinterr("probe expects <pck path> <pack id>")
\t\tquit(2)
\t\treturn
\tvar pack_path := arguments[0]
\tvar pack_id := arguments[1]
\tvar failures := 0
\tif not ProjectSettings.load_resource_pack(pack_path):
\t\tprinterr("Godot refused to mount %s" % pack_path)
\t\tquit(1)
\t\treturn
\tvar manifest_path := "res://packs/%s/pack.json" % pack_id
\tif not FileAccess.file_exists(manifest_path):
\t\tprinterr("the built pack carries no manifest at %s" % manifest_path)
\t\tquit(1)
\t\treturn
\tvar file := FileAccess.open(manifest_path, FileAccess.READ)
\tvar parsed: Variant = JSON.parse_string(file.get_as_text())
\tif not parsed is Dictionary:
\t\tprinterr("%s is not a JSON object once packed" % manifest_path)
\t\tfailures += 1
\telse:
\t\tvar manifest: Dictionary = parsed
\t\tif str(manifest.get("id", "")) != pack_id:
\t\t\tprinterr("%s declares id %s, not %s" % [manifest_path, str(manifest.get("id", "")), pack_id])
\t\t\tfailures += 1
\t\tfor asset in manifest.get("assets", []):
\t\t\tvar relative_path := str((asset as Dictionary).get("path", ""))
\t\t\tvar resolved := "res://packs/%s/%s" % [pack_id, relative_path]
\t\t\tif not FileAccess.file_exists(resolved):
\t\t\t\tprinterr("asset %s declares %s, which is not inside the built pack" % [str((asset as Dictionary).get("id", "")), relative_path])
\t\t\t\tfailures += 1
\tif failures == 0:
\t\tprint("Pack %s verified: manifest and every declared asset present at res://packs/%s/." % [pack_id, pack_id])
\tquit(1 if failures > 0 else 0)
`;

if (!existsSync(packsDirectory)) {
  fail(`there is no packs/ directory at ${relative(repo, packsDirectory)}`);
  process.exit(1);
}

const version = runGodot("engine check", ["--headless", "--version"]);
if (version === null) process.exit(1);
console.log(`build-pack: using ${godot} (${version.trim()})`);

await rm(stagingRoot, { recursive: true, force: true });
await mkdir(outputDirectory, { recursive: true });

await mkdir(probeProject, { recursive: true });
await writeFile(resolve(probeProject, "project.godot"), projectFile("Project 42 pack probe"));
await writeFile(resolve(probeProject, "verify_pack.gd"), PROBE_SCRIPT);
if (runGodot("probe project import", ["--headless", "--path", probeProject, "--import"]) === null) {
  process.exit(1);
}

const packDirectoryNames = (await readdir(packsDirectory, { withFileTypes: true }))
  .filter(entry => entry.isDirectory())
  .map(entry => entry.name)
  .sort();

let built = 0;
for (const directoryName of packDirectoryNames) {
  const manifestFile = resolve(packsDirectory, directoryName, "pack.json");
  // A directory under packs/ that carries no manifest is not a pack, which is
  // the same reading ContentPackRegistry.scan takes of one.
  if (!existsSync(manifestFile)) continue;

  const manifest = JSON.parse(await readFile(manifestFile, "utf8"));
  // The one schema fact this script depends on. tools/src/validate.mjs is the
  // pack schema's only validator and already checks this; it is re-read here
  // because the whole output path is built from it, and a mismatch would
  // produce a .pck the registry cannot find the manifest inside.
  if (manifest.id !== directoryName) {
    fail(`packs/${directoryName}/pack.json declares id ${manifest.id}; it must equal its directory name`);
    continue;
  }

  const staging = resolve(stagingRoot, directoryName);
  await mkdir(resolve(staging, "packs"), { recursive: true });
  await writeFile(resolve(staging, "project.godot"), projectFile(`Project 42 pack build: ${directoryName}`));
  await writeFile(resolve(staging, "export_presets.cfg"), EXPORT_PRESETS);
  await cp(resolve(packsDirectory, directoryName), resolve(staging, "packs", directoryName), { recursive: true });

  if (runGodot(`${directoryName}: import`, ["--headless", "--path", staging, "--import"]) === null) continue;

  const output = resolve(outputDirectory, `${directoryName}.pck`);
  if (runGodot(`${directoryName}: export-pack`, ["--headless", "--path", staging, "--export-pack", PRESET_NAME, output]) === null) continue;
  if (!existsSync(output)) {
    fail(`${directoryName}: the export reported success but wrote no ${relative(repo, output)}`);
    continue;
  }

  if (runGodot(`${directoryName}: verify`, ["--headless", "--path", probeProject, "--script", "res://verify_pack.gd", "--", output, directoryName]) === null) continue;

  console.log(`build-pack: ${relative(repo, output)}`);
  built += 1;
}

if (built === 0) {
  fail("no pack was built; packs/ carries no directory with a pack.json");
}
if (process.exitCode) {
  console.error("build-pack: failed.");
  process.exit(1);
}
console.log(`build-pack: ${built} pack${built === 1 ? "" : "s"} built into ${relative(repo, outputDirectory)}/.`);
