//! Provisional stand-in for the generated main-scenario document.
//!
//! Owner: lane `scenario-runtime-loading`. `scenario-pack-tooling` writes the
//! real document to `game/generated/scenarios/scenario.pirate_island.json`;
//! this module assembles the same document from the same source files so the
//! runtime's proofs can run before that lane lands. **Delete it on
//! integration** and let the tests read the generated file, which
//! `assembled_fixture_matches_generated_document` already compares against
//! whenever it is present.

use crate::world::{IslandPoint, ScenarioDefinition};
use std::collections::BTreeSet;

/// The generated document, assembled from the pack's referenced files.
pub fn main_scenario_document() -> String {
    let value = serde_json::json!({
        "format": "project42.scenario",
        "version": 1,
        "generatedFrom": "validated scenario pack; do not edit this file by hand",
        "scenario": {
            "schemaVersion": 1,
            "id": "scenario.pirate_island",
            "title": "Pirate Island",
            "summary": "The main scenario: five factions on one tropical island, Michael alone on the beach.",
            "geography": {
                "terrainTexture": "res://assets/island/terrain.png",
                "navigation": document("../../game/assets/island/navigation.json"),
            },
            "start": {
                "captainId": "character.protagonist.captain",
                "combatProfile": {"health": 30, "damage": 4, "range": 4, "cooldown_ticks": 5},
            },
            "factions": [
                faction("faction.colonial_powers.prototype", [12, 11], include_str!("../../content/production/colonial_fort_soldiers.json")),
                faction("faction.pirates.prototype", [35, 15], include_str!("../../content/production/tide_quay_deckhands.json")),
                faction("faction.cthulhu.prototype", [28, 23], include_str!("../../content/production/drowned_shrine_cultists.json")),
                faction("faction.eastern_fox_people.prototype", [33, 9], include_str!("../../content/production/eastern_fox_people_river_market_skirmishers.json")),
                faction("faction.elves.prototype", [13, 17], include_str!("../../content/production/elven_heart_grove_bow_wardens.json")),
            ],
            "rules": {
                "cthulhuMadness": document("../../content/island/cthulhu_madness.json"),
                "colonialExpansion": document("../../content/island/colonial_expansion.json"),
                "holdingRepairs": document("../../content/island/holding_repairs.json"),
                "holdingSalvage": document("../../content/island/holding_salvage.json"),
                "holdingDevelopment": document("../../content/island/holding_development.json"),
                "michaelFoothold": document("../../content/island/michael_foothold.json"),
                "michaelMachinery": document("../../content/island/michael_machinery.json"),
                "michaelMachineProduction": document("../../content/production/michael_field_workshop_mechanical_dogs.json"),
                "survivalDiplomacy": document("../../content/island/survival_diplomacy.json"),
                "initialDiplomacy": document("../../content/diplomacy/initial_relationships.prototype.json"),
            },
            "buildings": document("../../game/assets/island/buildings.json"),
            "personas": document("../../game/assets/island/personas.json"),
            "resources": [],
            "items": [],
            "triggers": [],
            "quests": [],
        }
    });
    value.to_string()
}

/// The main scenario with the land the Rust proofs run on.
pub fn main_scenario() -> ScenarioDefinition {
    let mut definition = ScenarioDefinition::from_document(&main_scenario_document())
        .expect("assembled main scenario document");
    assert!(definition.set_land(prototype_land(), IslandPoint { x: 8, y: 16 }));
    definition
}

/// The small elliptical island the simulation's proofs have always used. The
/// shipped island's land comes from the scenario's navigation polygon,
/// rasterised in GDScript; this fixture keeps the Rust proofs deterministic
/// without a second rasteriser.
pub fn prototype_land() -> BTreeSet<IslandPoint> {
    let mut land = BTreeSet::new();
    for x in 0..48 {
        for y in 0..32 {
            if (x - 24_i32).pow(2) * 196 + (y - 16_i32).pow(2) * 484 < 484 * 196 {
                land.insert(IslandPoint { x, y });
            }
        }
    }
    land
}

fn faction(id: &str, seed: [i32; 2], production: &str) -> serde_json::Value {
    let roster: serde_json::Value =
        serde_json::from_str(include_str!("../../content/island/faction_roster.json"))
            .expect("authored faction roster");
    serde_json::json!({
        "id": id,
        "seed": seed,
        "tuning": roster[id].clone(),
        "production": serde_json::from_str::<serde_json::Value>(production).expect("authored production rule"),
    })
}

macro_rules! document {
    ($path:literal) => {
        serde_json::from_str::<serde_json::Value>(include_str!($path)).expect("authored document")
    };
}

fn document(path: &str) -> serde_json::Value {
    match path {
        "../../game/assets/island/navigation.json" => {
            document!("../../game/assets/island/navigation.json")
        }
        "../../content/island/cthulhu_madness.json" => {
            document!("../../content/island/cthulhu_madness.json")
        }
        "../../content/island/colonial_expansion.json" => {
            document!("../../content/island/colonial_expansion.json")
        }
        "../../content/island/holding_repairs.json" => {
            document!("../../content/island/holding_repairs.json")
        }
        "../../content/island/holding_salvage.json" => {
            document!("../../content/island/holding_salvage.json")
        }
        "../../content/island/holding_development.json" => {
            document!("../../content/island/holding_development.json")
        }
        "../../content/island/michael_foothold.json" => {
            document!("../../content/island/michael_foothold.json")
        }
        "../../content/island/michael_machinery.json" => {
            document!("../../content/island/michael_machinery.json")
        }
        "../../content/production/michael_field_workshop_mechanical_dogs.json" => {
            document!("../../content/production/michael_field_workshop_mechanical_dogs.json")
        }
        "../../content/island/survival_diplomacy.json" => {
            document!("../../content/island/survival_diplomacy.json")
        }
        "../../content/diplomacy/initial_relationships.prototype.json" => {
            document!("../../content/diplomacy/initial_relationships.prototype.json")
        }
        "../../game/assets/island/buildings.json" => {
            document!("../../game/assets/island/buildings.json")
        }
        "../../game/assets/island/personas.json" => {
            document!("../../game/assets/island/personas.json")
        }
        other => panic!("unknown scenario document {other}"),
    }
}
