extends SceneTree

func _initialize() -> void:
	var catalog := ContentCatalog.new()
	assert(catalog.load_default() == OK)
	assert(catalog.has("presentation.camera.registry"))
	assert(catalog.has_registry_entry("presentation.camera.impact_punch_in"))
	assert(catalog.has("presentation.vfx.registry"))
	assert(catalog.has_registry_entry("presentation.vfx.bronze_teal_impact_arc"))
	assert(catalog.has("presentation.motion.registry"))
	assert(catalog.has_registry_entry("presentation.motion.betty.ready_idle"))
	var camera := catalog.get_registry_entry("presentation.camera.impact_punch_in")
	assert(camera.mode == "punch")
	assert(camera.zoom == 1.12)
	assert(camera.safePaddingPercent >= 8)
	assert("impact_arc" in camera.focusSubjects)
	var copy := catalog.get_registry_entry("presentation.camera.impact_punch_in")
	copy.zoom = 99.0
	assert(catalog.get_registry_entry("presentation.camera.impact_punch_in").zoom == 1.12)
	var vfx := catalog.get_registry_entry("presentation.vfx.bronze_teal_impact_arc")
	assert(vfx.purpose.length() > 10)
	assert(vfx.safeFrameOverflowAllowed == false)
	assert(vfx.envelopeWidthPercent > 0)
	var vfx_copy := catalog.get_registry_entry("presentation.vfx.bronze_teal_impact_arc")
	vfx_copy.persistenceMs = 9999
	assert(catalog.get_registry_entry("presentation.vfx.bronze_teal_impact_arc").persistenceMs != 9999)
	var ready_idle := catalog.get_registry_entry("presentation.motion.betty.ready_idle")
	assert(ready_idle.sourceProvider == "magnific")
	assert(ready_idle.loopMode == "seamless_repeat")
	assert(ready_idle.safePaddingPercent == 8)
	assert(ready_idle.importState == "source_downloaded_needs_runtime_transcode")
	assert(ready_idle.runtimePath == "")
	print("ContentCatalog registry tests passed.")
	quit(0)
